set(SUBCATEGORY_NAME SurfaceDetailing)

add_subdirectory(Base)
include_directories(Base)

add_subdirectory(BumpMapping)
add_subdirectory(NormalMapping)
add_subdirectory(BasicDisplacement)
add_subdirectory(ParallaxOffsetMapping)
add_subdirectory(SteepParallaxMapping)
add_subdirectory(ParallaxOcclusionMapping)