set(SUBCATEGORY_NAME TessellationShaders)

add_subdirectory(Base)
include_directories(Base)

add_subdirectory(BasicTriangleTessellation)
add_subdirectory(DisplacementMappingTessellation)
add_subdirectory(TerrainHeightmapTessellation)
add_subdirectory(CubicBezierCurveTessellation)
add_subdirectory(BezierSurfaceTessellation)
add_subdirectory(CurvedPnTrianglesTessellation)
