#version 450

// ------------------------------------------------------------------------
// Author: Mustafa Yemural
// Description:
// ------------------------------------------------------------------------
// Copyright (c) 2025 Mustafa Yemural - www.mustafayemural.com
// Licensed under the MIT License.
// ------------------------------------------------------------------------

layout(triangles, equal_spacing, ccw) in;

void main()
{
    // gl_TessCoord: (u, v, w) barycentric coordinates, generated by GPU
    vec3 bary = gl_TessCoord;

    vec4 pos = bary.x * gl_in[0].gl_Position +
    bary.y * gl_in[1].gl_Position +
    bary.z * gl_in[2].gl_Position;

    gl_Position = pos;
}
