set(SUBCATEGORY_NAME QueriesAndPerformance)

add_subdirectory(Base)
include_directories(Base)

add_subdirectory(OcclusionQuery)
add_subdirectory(TimestampQuery)
add_subdirectory(PipelineStatisticsQuery)
add_subdirectory(DynamicUniformBuffer)
add_subdirectory(BufferSuballocation)
add_subdirectory(IndirectDrawing)