set(SUBCATEGORY_NAME ShadowFilteringAndSoftening)

add_subdirectory(Base)
include_directories(Base)

add_subdirectory(PercentageCloserFiltering)
add_subdirectory(HardwarePercentageCloserFiltering)
add_subdirectory(ExponentialShadowMapping)
add_subdirectory(VarianceShadowMapping)
add_subdirectory(ExponentialVarianceShadow)
add_subdirectory(PercentageCloserSoftShadows)
add_subdirectory(ExponentialVarianceWithGaussian)