set(SUBCATEGORY_NAME GeometryShaders)

add_subdirectory(Base)
include_directories(Base)

add_subdirectory(SimplePrimitiveGeneration)
add_subdirectory(ObjectExplosion)
add_subdirectory(NormalVectorVisualization)
add_subdirectory(WireframeOverlayVisualization)
add_subdirectory(SinglePassCubemapRendering)
add_subdirectory(ViewportArraysGeometry)
add_subdirectory(BillboardingGeometryShader)
add_subdirectory(GrassGenerationGeometry)
