set(SUBCATEGORY_NAME AdvancedComputeShaders)

add_subdirectory(Base)
include_directories(Base)

add_subdirectory(GameOfLifeSubgroup)
add_subdirectory(OcclusionCullingCompute)
add_subdirectory(BodyParticleCompute)
add_subdirectory(WindSimulationFoliage)
add_subdirectory(ClothSimulationCompute)
add_subdirectory(FftOceanCompute)
